In [1]:
import numpy as np

In [9]:
a=[1,2,3]
print(a)
print(len(a))
print(type(a))
print()
a=np.array([1,2,3])
print(a)
print(a.shape)
print(type(a))
b=np.array([[1,2,3]])
print(b.shape)

[1, 2, 3]
3
<class 'list'>

[1 2 3]
(3,)
<class 'numpy.ndarray'>
(1, 3)


In [3]:
a.reshape([3,1])

array([[1],
       [2],
       [3]])

In [9]:
b=np.array([[1],[2],[3]])
print(b)
print(b.shape)
print(type(b))

[[1]
 [2]
 [3]]
(3, 1)
<class 'numpy.ndarray'>


In [21]:
b=b.reshape([-1, ]) # or b.reshape(-1)
print(b)
print(b.shape)
print(type(b))

[1 2 3]
(3,)
<class 'numpy.ndarray'>


In [24]:
d=np.array([[1,2],[3,4],[4,5]])
print(d)
d=d.reshape([-1, 1]) # or b.reshape(-1)
print(d)
print(d.shape)
print(type(d))

[[1 2]
 [3 4]
 [4 5]]
[[1]
 [2]
 [3]
 [4]
 [4]
 [5]]
(6, 1)
<class 'numpy.ndarray'>


In [3]:
c=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(c)
print(c.shape)
print(type(c))
print(c.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
<class 'numpy.ndarray'>
2
